### ISSUE TITLE
Vytvorenie katalógu špecifikácií

### ISSUE THREAD

**Issue by TheTimeBandit** [TIS2018-FMFI/rebricek-bezcov#1]

**Comment by TheTimeBandit** [comment]
**Dôležité: Niektoré z týchto bodov nie sú platné, pretože sa úplne zmenila predstava riešenia**

---

aktualna predstava
---
 (ktoru by bolo dobre zachytit aj v bode _2._ ):
 **medzivysledok je len docasny po dobu vygenerovania vysledku a vzdy sa generuje nanovozo vsetkych kol, ktore su reprezentovane subormi v podadresari danej sezony, platna sezona je uvedena v konfigu
 hint: mohlo by byt podobne aj Pavol / Pavel**

---

- [x]  v 1.1. pre koho je urceny dokument
- [x] 1.2. zadavatela vs. pouzivatela
- [x] 1.2. nedalo by sa doplnit dve slova, aby to bolo este zrozumitelnejsie?
- [x] 1.3. formatovat slova v slovniku kurzivou alebo podobne
- [x] 3.1. udalost - identifier not found, rozpis -> zoznam, zoznam pretekarov dvojbodka
- [x] cas, alebo informacia, ze bol diskvalifikovany.
- [x] pridat vetu: System akceptuje aj vstup, kde pre niektorych pretekarov nie je zadana informacia: ???(presne uviest vsetky mozne pripady, aby to bolo celkom jednoznacne)
- [x] zvazit: 3.2.1.4 ak meno vstupneho suboru v konfiguracnom subore nie je uvedene, program si ho vypyta z konzoly po spusteni
- [ ] 3.4. umiestnenie, cize aktualne poradie v sezone
- [x] 3.2.2.3. prvy bod:  Ak sa v medzivýsledkoch pretekár s rovnakým kódom nenachádza, tak upozorní používateľa a postupuje podľa nasledujúceho bodu.
- [x] druhy bod: 
- (teraz) Ak v dátach bežca nie je zadaný registračný kód, tak sa najprv program pokúsi nájsť v medzivýsledkoch všetkých bežcov s rovnakým menom.
- (upravit)=>Ak v dátach bežca nie je zadaný registračný kód, tak sa najprv program pokúsi nájsť v medzivýsledkoch všetkých bežcov s rovnakým alebo podobným menom.

**Comment by TheTimeBandit** [comment]
časť 3.3.1 nedáva zmysel, prepracujte to niekto

**Comment by jozefmizerik** [comment]
co ti tam nedava zmysel

**Comment by TheTimeBandit** [comment]
Pozerám, že si to už upravil.
Ale stále je to nepresné, ako napríklad "Program bude obsahovať priečinok ..."

**Comment by jozefmizerik** [comment]
Monika to upravovala. A čo sa týka:
 zvazit: 3.2.1.4 ak meno vstupneho suboru v konfiguracnom subore nie je uvedene, program si ho vypyta z konzoly po spusteni
nezapametal si si to nahodou zle? mne sa zda, ze chcel aby to bolo z command linu, nie z konzoly

**Comment by monikavlckova** [comment]
prerobila som to

**Comment by TheTimeBandit** [comment]
spisal som to najdolezitejsie, čo bezodkladne treba doriešiť
**SUMARIZACIA**

Treba domyslieť: a zvážiť:

- adresa vstupneho suboru na pridanie v konfiguracnom subore _alebo_  zadana v konzole
(manualne urcite nie, lebo v tom pripade by musel pouzivatel manualne aj vytvarat priecinky so spravnymi menami)

- pouzivatel musi vediet vygenerovat html subor aj bez pridania kola
(mozno hned pri spusteni sa ho program opyta, ci chce vygenerovat subor alebo pridat kolo)

-  command line argumenty

**Comment by TheTimeBandit** [comment]
Update:
- v sezone je iba jedna sutaz a to Sanasport Cup
- v konfiguracnom je: rok sezony a typ bodovania

**Comment by trizna3** [comment]
upravil som časť 3.4, Jozko pozri to prosim.

**Comment by TheTimeBandit** [comment]
Špecifikácia požiadaviek odoslaná cvičiacemu na skontrolovanie. 
Uzatváram issue.
Ak sa nájdu nejaké nedostatky, bude na to nové issue.

**Comment by TheTimeBandit** [comment]
Špecifikácia požiadaviek (verzia 4) bola schválená zadávateľom.
