### ISSUE TITLE
Návrh: používateľské rozhranie (GUI)

### ISSUE THREAD

**Issue by TheTimeBandit** [TIS2018-FMFI/rebricek-bezcov#11]

**Comment by trizna3** [comment]
Kapitola návrhu "4. Návrh používateľského rozhrania" je hotová. Je tam spomenutá aj nová funkcionalita (kompletne popísaná je v 'Spúštacom module'), ktorá bola navrhnutá na poslednom stredajšom stretnutí - program je možné spustiť z príkazového riadku s parametrom('-a [adresa]' alebo '-b').
