### ISSUE TITLE
Návrh: implementácia - UML component diagram

### ISSUE THREAD

**Issue by TheTimeBandit** [TIS2018-FMFI/rebricek-bezcov#15]

**Comment by trizna3** [comment]
Component diagram pridany do branchu 'Dokumentacia' do priecinku 'documentation/diagrams'. Idealne si ho skontrolujme v stredu na stretnuti.

**Comment by trizna3** [comment]
Do branchu 'Dokumentacia' do priecinku 'documentation/diagrams' som pridal dalsiu verziu Component diagramu. (v2)

**Comment by trizna3** [comment]
po zhodnoteni diagramu na poslednom stredajsom stretnuti (5.12) este upravim vzhlad diagramu (do 12.12)

**Comment by trizna3** [comment]
diagram upraveny (hranate hrany, rozhrania presunute k modulom, ktore ich poskytuju), nahrany do branchu dokumentacia, do priecinku documentation/diagrams. zatvaram issue
