### ISSUE TITLE
Návrh: implementácia - UML class diagram

### ISSUE THREAD

**Issue by TheTimeBandit** [TIS2018-FMFI/rebricek-bezcov#16]
Class diagram je možné vygenerovať priamo v IDE IntelliJ
návod tu: [**IntelliJ IDEA - Class Diagram**](https://www.jetbrains.com/help/idea/class-diagram.html)

**Comment by trizna3** [comment]
do stredy (12.12) prosim vsetci nahrajme co najrozsiahlejsie kostry tried (hlavicky tried a metod) svojich modulov do githubu.

**Comment by trizna3** [comment]
v branchi 'Interaction-&-InputCheck-Modules' su nahrane zdrojove subory **Spustacieho** a **Interakcneho** modulu - vyrazny kus implementacie este chyba, ale triedy maju definovane hlavicky vsetkych podstatnych metod, takze su pripravene pre generovanie class diagramu.

**Comment by jozefmizerik** [comment]
aj za mna hotovo, do mojej branche som nahral uz aj priradovaci modul. Mam tam akurat este package testing, ktory pouzivam iba interne na testovanie, tak ten potom nedavajte do class diagramu

**Comment by TheTimeBandit** [comment]
Veľmi zhruba som načrtol  InputFileClasses(xml -> objekty), InputFileHandlingModule(práca so vstup. subormy) a DataVerificationModule (kontrola vstupneho suboru).
Moduly zatiaľ majú pokryté len rozhrania a ostatné private metódy doplním čo najskôr podľa možnosti.

**Comment by monikavlckova** [comment]
Ja som už tiež nahrala.

**Comment by TheTimeBandit** [comment]
Prvá verzia class diagramu je v dokumentácii

**Comment by pavelpetrovic** [comment]
Pekne, dakujem.
Prosim Vas, taketo veci vzdy robte s bielym pozadim. 
Ked by to nahodou niekto chcel v nejakej podobe tlacit, tak tmave pozadie je nanic.
Ak uz inak nie, tak v GIMPe staci urobit Colors - Invert a Colors - Map - Colors Exchange.
p.

**Comment by TheTimeBandit** [comment]
Hned po nahrati tmaveho som vytvoril biely, zo zjavných dôvodov a pridal som ho do návrhu, 
vo vetve dokumentácie sa tiež už nachádza biely diagram
