### ISSUE TITLE
Návrh: implementácia - architektúra

### ISSUE THREAD

**Issue by TheTimeBandit** [TIS2018-FMFI/rebricek-bezcov#18]

**Comment by trizna3** [comment]
@TheTimeBandit Tomas, prosimta co konkretne zahrna toto issue? (nie som si isty) dik

**Comment by TheTimeBandit** [comment]
Issues boli vytvorené z popisu na stránke predmetu,
Celkovo myslím, že v našom prípade to je rozdelenie na moduly.
