### ISSUE TITLE
Návrh: implementácia - moduly a ich interfaces(rozhrania)

### ISSUE THREAD

**Issue by TheTimeBandit** [TIS2018-FMFI/rebricek-bezcov#19]

**Comment by jozefmizerik** [comment]
Mne si na stretku myslím povedal Tomáš, že výstupom tvojich modulov bude trieda Kolo, obsahujúca mnozinu objektov Kategória a Kategória obsahuje zoznam objektov triedy Pretekár. Nikde v tvojej časti návrhu som o tom nenašiel ani zmienku, tak neviem teraz či si to ešte neurobil alebo si to nebodaj nejak zmenil a mne nedal vedieť, nakoľko mám už nakódený výpočtový modul podľa toho.

**Comment by TheTimeBandit** [comment]
Kolo je a stále bolo len pracovným názvom, označujúcim triedu **ResultList**.
Moja časť návrhu popisuje unmarshalovanie vstupného dokumentu formátu XML do objektu triedy.

Na stretnutiach som vysvetloval štruktúru vstupného dokumentu a proces un/marshalovania:
Názov triedy ResultList pochádza z názvu koreňového elementu vstupného súboru formátu XML.
Rovnako aj ostatné triedy, ktoré vzniknú unmarshalovaním budú mať názvy zodpovedajúce názvom elementov v XML dokumente, aby to nebolo chaotické a dalo sa v tom do budúcna vyznať. 
(Výnimkou je element Class, pre ktorý bude mať java trieda odlišný názov, pretože trieda Class už existuje)

Každopádne ti odporúčam naštudovať si štruktúru vstupného dokumentu, keďže veľmi podobnú štruktúru bude mať objekt triedy ResultList, ktorý bude _Modul na prácu so vstupnými súbormi_ poskytovať ostatným modulom.

**Comment by TheTimeBandit** [comment]
A dohodli sme sa na tom, že implementácia bude v spoločnom jazyku - **angličtine**. 
Takže názvy tried, premenných a funkcií budú v angličtine
**Kolo, Kategória, Pretekár ako názvy tried** by sa teda nemali vyskytnúť.

**Comment by jozefmizerik** [comment]
ok, mám ešte jeden návrh na zefektívnenie programu.. Ty vytváraš nejaké inštancie pretekárov, ktoré budú obsahovať údaje z toho xml vrátane ich času za ktorí zabehli kolo... ja dopočítavam potom vo výpočtovom module podľa toho položku body. Preto keby vytváram nejaké svoje nové inštancie pretekárov, zbytočne by to zaťažovalo beh programu. Ideálne by bolo keby iba k tvojim inštanciam pretakarov priradim body a tie by sa posunuli zase dalej priradovaciemu modulu. Takže by bolo dobre, keby si kazdemu pretekarovi dal atribut body inicializoval ho na 0. A ja by som ho potom cez nejaky setter nastavil

**Comment by jozefmizerik** [comment]
ok, mám ešte jeden návrh na zefektívnenie programu.. Ty vytváraš nejaké inštancie pretekárov, ktoré budú obsahovať údaje z toho xml vrátane ich času, za ktorý zabehli kolo... ja dopočítavam potom vo výpočtovom module podľa toho položku body. Preto keby vytváram nejaké svoje nové inštancie pretekárov, zbytočne by to zaťažovalo beh programu. Ideálne by bolo keby iba k tvojim inštanciam pretakarov priradim body a tie by sa posunuli zase dalej priradovaciemu modulu. Takže by bolo dobre, keby si kazdemu pretekarovi dal atribut body inicializoval ho na 0. A ja by som ho potom cez nejaky setter nastavil

**Comment by TheTimeBandit** [comment]
Keďže atribút počet bodov sa nenachádza ako XML element tak to môže robiť problémy.
Tie triedy, do ktorých sa mapujú XML elementy by nemali mať premenné bez anotácie.
Skúsme radšej porozmýšlať nad iným riešením a k tomuto sa vráťme, keď sa nič iné nenájde.

UPDATE: Prípadne môže vzniknúť nový modul, ktorý po prečítaní vstupného dokumentu vytvorí nové objekty tried, kam sa presunú potrebné údaje a budú mať aj navyše údaje ako počet bodov, zmena pozície, ....

**Comment by jozefmizerik** [comment]
Ak to nejde netreba dalši modul, tych už mame dosť. Dám to do výpočtového keď tak.

**Comment by jozefmizerik** [comment]
Tomáš, ešte mi celkom nie je jasné to tvoje rozdelenie tu:
https://github.com/TIS2018-FMFI/rebricek-bezcov/tree/InputFileHandling-%26-DataVerification-Modules/rebricek-bezcov/src/InputFileClasses
Teda najvyššiu triedu máš resultList.  Potom nasleduje ClassResult? to su ako vysledky jednotlivych kategórií?
A potom PersonResult výsledky jednotlivých pretekárov? a aký je rozdiel medzi triedami Person a PersonResult?

**Comment by TheTimeBandit** [comment]
Najlepšie bude, keď sa pozrieš na vstupný súbor. 

ResultList má v sebe Event a zoznam ClassResult:List (zoznam kategórií).
Event reprezentuje informácie o kole, 
Jeden objekt triedy ClassResult reprezentuje informácie o jednej kategórii.

ClassResult má v sebe ClassDetail (v XML je to element Class)  a zoznam PersonResult: List (pretekáry v kategórii)
ClassDetail popisuje informácie o kategórii( id a názov(napr. M-40))
PersonResult popisuje zúčastneného pretekára.

PersonResult má v sebe triedy Person a Result.
Person popisuje osobné údaje o pretekára(id, meno, priezvisko)
Result popisuje výkon pretekára v kole(cas, pozicia, status)

Ak mi to java povolí(ak to nebude keyword ako Class), tak sa posnažím dať aj názvy atribútov rovnaké ako majú elementy vo vstupnom súbore, a teda aj gettery by mali byť rovnaké.

**Comment by trizna3** [comment]
Toto issue takisto uzavrime do stredy (12.12).
Ide o popis metod, ktorymi akokolvek komunikuju dva moduly medzi sebou. Idealne pridat popis rozhrania k popisu modulu, ktory rozhranie poskytuje (prakticky je to ten modul, ktoreho metody sa volaju).
Taktiez nieje na skodu, ak niekde v navrhu najdeme tento dohodnuty format dát, o ktorom sa tu dohadovalo v komentaroch issue.
dik
