### ISSUE TITLE
Návrh: implementácia - použité technológie

### ISSUE THREAD

**Issue by TheTimeBandit** [TIS2018-FMFI/rebricek-bezcov#20]

**Comment by trizna3** [comment]
Toto sa mozme snazit uzavriet do stredy (12.12).
Neviem ci su este nejake technologie, ktore budu pouzivane a niesu este uvedene v navrhu.
@monikavlckova mozno, su tam este nejake otazniky nad tym, ako budeme generovat ten vystup (a teda ake technologie sa budu vyuzivat)? dakujem
Popripade ak nikto iny uz nic nema, mozme issue zavriet. dik

**Comment by monikavlckova** [comment]
ja nebudem pouzivat ziadne specialne technologie, tomas cosi pouziva a to tam je popisane takze si myslim ze sa to moze zavriet
