### ISSUE TITLE
Specifikacia: pripomienky - praca s chybajucimi udajmi vo vstupnych xml subore

### ISSUE THREAD

**Issue by TheTimeBandit** [TIS2018-FMFI/rebricek-bezcov#25]
Ak pri čítaní vstupného xml suboru nebude pre niektorý z údajov: cislo kola, nazov kola, datum kola, zadaný príslušný tag <Name> alebo <Date> alebo nebude mat spravny parsovatelny format, tak program na to upozorni pouzivatela cez konzolu a vyzve ho doplnit tento udaj do konzoly. Potom tento udaj vloží do xml suboru.

Program vytvori tento tag, ak chyba, alebo ak je iba nespravne zadany, tak ho prepise v xml,

Vyber riesenia: Prezerat tieto udaje pri pridavani suboru, alebo az pri prechadzani vsetkymi subormi,
**prípadne v obidvoch prípadoch** ?

**Comment by pavelpetrovic** [comment]
dufam, ze niekde je presne uvedene, co je "dolezity udaj".

**Comment by TheTimeBandit** [comment]
samozrejme, vsetky detaily su v sprave od zadavatela, 
 ďakujem za pripomienku, upravím to

**Comment by TheTimeBandit** [comment]
Požiadavku som spracoval.
