### ISSUE TITLE
Návrh: Výpočtový modul

### ISSUE THREAD

**Issue by TheTimeBandit** [TIS2018-FMFI/rebricek-bezcov#30]
- aplikovanie zvolenej metody, určenej v konfiguračnom subore, a nasledne priradovanie bodov

**Comment by jozefmizerik** [comment]
co mas namysli tym "priradenim pretekarov" ?

**Comment by TheTimeBandit** [comment]
Keď bol pretekár napriklad v dvoch kolách, tak vo výsledku bude mať výsledný počet bodov ako súčet tých dvoch kôl, teda je potrebné priradiť údaje pretekára z prvého kola k údajom z druhého kola, ok? 
Teda poriešiť priradenie podla mena/registračného kódu.

**Comment by jozefmizerik** [comment]
Ale nespominam si, ze by sme sa dohodli, ze aj toto budem robit ja

**Comment by TheTimeBandit** [comment]
To je presne tá vec, ktorú sme sa dohodli, že budeš robiť, to je ten "Výpočet", čo je aj v názve modulu.

**Comment by jozefmizerik** [comment]
Ale ja mam pocitat body a nie parsovat pretekarov. Ide mi teraz hlavne o to, ze ja nemam robit este aj to rozlisenie, ze ci je J.Novak a Jan Novak ten isty pretekar. To nema nic s vypoctami, tam sa bude muset parsovat text. Podla mna to ani nepatri do vypoctoveho modulu.

**Comment by trizna3** [comment]
Ja som tiež pochopil 'Výpočet' len ako aplikáciu algoritmov na čísla .. priznám sa, že na toto priradzovanie pretekarov k výsledkom iných kôl som aj pozabudol. 

Teda k tomu rozdeleniu práce - tak ako sme si to povedali naposledy to bol podľa mňa približný nástrel .. teda by som sa kvôli tomu nehádal, kto čo musí/nemusí. Jožko ak už pracuješ/ideš pracovať na nejakej implementácii, kludne sa zameraj na ten výpočet tak, ako si hovoril. Myslim, že určite to rozdelenie, ktoré sme spravili nieje uplne rovnomerné, takže si ešte neskôr, keď už niečo bude spravené rozdelíme ďalšiu robotu.

K tým bodom, čo vyššie píše Tomáš: myslím, že toto priradzovanie sa musí robiť ešte pred samotným výpočtom, nie? dik

**Comment by TheTimeBandit** [comment]
Vytvoril som nové issue pre "Priradzovací modul"

**Comment by jozefmizerik** [comment]
Ok, dik, myslim, si, ze to bude lepsie mimo. Trocha to odlahci vypoctovy modul, ktory bude beztak rozsiahly. A kludne by som to zatial nepriradzoval nikomu, uvidime casom kde sa to najviac bude hodit. Nevylucujem, ze to spravim nakoniec ja.

**Comment by trizna3** [comment]
mozno je to uz len formalita, skusme uzavriet issue (do stredy 12.12)
