### ISSUE TITLE
Návrh: Priraďovací modul

### ISSUE THREAD

**Issue by TheTimeBandit** [TIS2018-FMFI/rebricek-bezcov#32]
- priradovanie údajov pretekárov viacerých kôl podla mena/reg.kodu

**Comment by jozefmizerik** [comment]
Začal som už pracovať na tomto module, snáď to stihnem dať do stredy ako-tak dokopy.

**Comment by trizna3** [comment]
mozno je to uz len formalita, skusme uzavriet issue (do stredy 12.12)

**Comment by jozefmizerik** [comment]
jj ako do zajtra to isto uzaverem, kedy mu to idete posialat?

**Comment by trizna3** [comment]
ja by som bol rad, keby sme to poslali az zajtra vecer (podla toho, ako si standartne rozvrhujem veci na tom vacsinou robim az v stredu v priebehu dna..)
