### ISSUE TITLE
Návrh - UML Use-Case Diagram

### ISSUE THREAD

**Issue by jozefmizerik** [TIS2018-FMFI/rebricek-bezcov#37]
Prerobil som use-case diagram
[useCase.pdf](https://github.com/TIS2018-FMFI/rebricek-bezcov/files/2609362/useCase.pdf)

**Comment by jozefmizerik** [comment]
Všimol som si, že aj ty si to prerábal Tomáš, ale chýba ti tam niečo. Ja som to prerobil presne podľa pripomienok cvičiaceho.

**Comment by TheTimeBandit** [comment]
pridaj to, prosím, ako obrázok, nech to pôjde ľahšie vložiť do návrhu.

**Comment by jozefmizerik** [comment]
![usecase](https://user-images.githubusercontent.com/40183056/48982465-4921e280-f0e3-11e8-8443-ac48cf6c231a.png)

**Comment by jozefmizerik** [comment]
pridal som do dokumentácie

**Comment by pavelpetrovic** [comment]
Jozef, sipka pri use-case ide od konkretizacie use-case ku vseobecnejsiemu use-case. Mam pocit, ze v tom prilozenom subore ide opacne, skontrolujte to, prosim.

**Comment by jozefmizerik** [comment]
Ďakujem za upozornenie, opravené
