### ISSUE TITLE
Stretnutie 27.11

### ISSUE THREAD

**Issue by jozefmizerik** [TIS2018-FMFI/rebricek-bezcov#41]
Dá sa vám ostať zajtra po prednáške chvíľu? nemalo by to byť nadlho

**Comment by TheTimeBandit** [comment]
Po TIS máme Úvod do bakalárskej práce, a tam je dôležité byť.
Takže zajtra to bude problematické urobiť stretnutie. Adam a Monika majú po UdBP aj Programovacie Paradigmy. 
Vyhovuje niekomu teda začiatok stretnutia o 14:50, prípadne aj neskôr ?

**Comment by jozefmizerik** [comment]
Mne sa zajtra potom uz jedine da tak od 16:00 do 16:30

**Comment by trizna3** [comment]
uf, ja mam zajtra hodiny od 8:00 až do 16:30, potom utekám so psom k veterinárovi.. teda ja niesom úplne spôsobilý

**Comment by jozefmizerik** [comment]
tak zajtra nic
