### ISSUE TITLE
Vytvoriť rôzne verzie konfiguračných súborov a uploadnuť ich

### ISSUE THREAD

**Issue by TheTimeBandit** [TIS2018-FMFI/rebricek-bezcov#51]

**Comment by jozefmizerik** [comment]
Config je tu, uplne dole: https://github.com/TIS2018-FMFI/rebricek-bezcov/tree/Computation-%26-Configuration-Modules(Jozko)/RebricekBezcov
A rôzne verzie nechápem, pri testovaní stačí meniť atribúty.
