### ISSUE TITLE
Návrh ( do 13.11. )

### ISSUE THREAD

**Issue by TheTimeBandit** [TIS2018-FMFI/rebricek-bezcov#6]
Návrh, všetko hotovo najneskôr do 13.11.

Musí obsahovať nasledujúce časti: 

- [ ] A.
podrobná špecifikácia vonkajších interfejsov - ak aplikácia komunikuje s inými aplikáciami, súbormi, zariadeniami - tieto musia byť jasne a podrobne definované

- [ ] B.
podrobný dátový model perzistentných údajov, formátov súborov, komunikačných protokolov.

- [ ] C.
návrh používateľského rozhrania (ak projekt má GUI) - nakreslené a popísané všetky dialógy, okná a stránky, ktorými aplikácia komunikuje s používateľom - túto časť treba konzultovať so zadávateľom

- [ ] D.
Zrozumiteľný a jednoznačný návrh implementácie, podľa ktorého sa dá aplikácia vyvinúť a ktorý bude obsahovať: UML component diagram, UML class diagram, a aspoň jeden z dvojice UML state a UML sequence diagram, zrozumiteľne vysvetlenú architektúru, rozdelenie na časti (moduly) a ich interfejsy, využité technológie, cieľové prostredie nasadenia do prevádzky.

**Comment by TheTimeBandit** [comment]
boli vytvorené samostatné issues pre časti A, B, C, D

**Comment by TheTimeBandit** [comment]
https://liveuniba-my.sharepoint.com/:w:/r/personal/takacs34_uniba_sk/_layouts/15/Doc.aspx?sourcedoc=%7B7C2D0B55-53A0-458E-8993-23EDF9F63D5E%7D&file=Navrh_v1.docx&action=default&mobileredirect=true

**Comment by pavelpetrovic** [comment]
nevidim ziadne issues tykajuce sa implementacie
v navrhu chyba uz iba rozhrania medzi modulmi, pripadne krajsie nazvy sprav v sekvencnom diagrame, komponentny diagram
vysledok by mal byt schvaleny navrh buduci tyzden
 
hlavna uloha: Monika vytvori demo ako sa da generovat HTML subor vo freemakeri uz vo formate ako je pozadovany

vznikaju aj testovacie scenare - mal by to byt samostatny dokument z dvoch casti pozostavajuci:
1. cast - kazdy za seba napise o svojich moduloch, ktore vyvija, ako ich bude testovat predtym ako ich da ostatnym ako "hotove"
- napr. zoznam unit-testov, ktore si clovek vyrobil s kratkym popisom co ktory robi alebo poradim v akom sa pustaju
podla tohto dokumentu by aj novy vyvojar, ktory urobi v kode zmeny mal byt schopny system pretestovat znovu
2. cast - subor testovacich scenarov - postupnost krokov akcia/vysledok, ktore spolu pokryvaju vsetky poziadavky v katalogu poziadaviek
(cim skor vznikne tym lepsie, ale je to timova zalezitost)
