### ISSUE TITLE
Rozdelit tvorbu navrhu medzi clenov

### ISSUE THREAD

**Issue by TheTimeBandit** [TIS2018-FMFI/rebricek-bezcov#8]

**Comment by pavelpetrovic** [comment]
zo stretnutia moje poznamky:


tim nevie vysvetlit v akom stave je KP ani 21.11. |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | --
potrebujem formalny suhlas zadavatela z poslednou verziou KP, ze si ho prestudoval a suhlasi s nim |   |   |   |   |   |  
Adam | popis modulov v navrhu a ich interfejsy, pripravoval strukturu implementacie |   |   |   |   |  
Tomáš | neptritomny a neospravedlneny |   |   |   |   |  
Jozef | popis modulov v navrhu a ich interfejsy, pripravoval strukturu implementacie |   |   |   |   |  
Monika | je zamerana na html vystup |   |   |   |   |  
  |   |   |   |   |   |  
vsetka komunikacia o praci ma prebiehat cez issues |   |   |   |   |   |  
v zapisnici nie su uvedene zodpovednosti clenov za ulohy, |   |   |   |   |   |  
vysledok prace na stretnuti je uvedeny len ako jedna veta bez konkretneho vysvetlenia co s tym dalej, kde to je a pod. |   |   |   |   |   |  
  |   |   |   |   |   |  
nabuduce si pozrieme hotovy navrh a schvalime ho |   |   |   |   |   |
