### ISSUE TITLE
Návrh:  špecifikácia vonkajších interfejsov

### ISSUE THREAD

**Issue by TheTimeBandit** [TIS2018-FMFI/rebricek-bezcov#9]
podrobná špecifikácia vonkajších interfejsov - ak aplikácia komunikuje s inými aplikáciami, súbormi, zariadeniami - tieto musia byť jasne a podrobne definované

**Comment by trizna3** [comment]
uzavrime issue do stredy (12.12).
Neviem, ako moc sa nas to tyka, @monikavlckova doplni popis struktury templatov.

**Comment by monikavlckova** [comment]
uz som to doplnila cize zatvaram issiu
